### ISSUE TITLE
Only Raw EEG data getting captured.

### ISSUE THREAD

**Issue by saipm1** [gmierz/mindwave-lsl#2]
Headers are written to the out put file. Only Raw EEG column is being captured. Rest of the data captured is NaN. I just used the command c:\ mindwavelsl --output sampleoutput.

**Comment by saipm1** [comment]
Can you help? Am I doing something wrong here?

**Comment by gmierz** [comment]
@saipm1 Hmm, I think if you remove this line you should be able to see the others better: https://github.com/gmierz/mindwave-lsl/blob/master/mindwavelsl/mindwavelsl.py#L39

Have a look at this example test file: https://github.com/gmierz/mindwave-lsl/blob/master/test_mouse_movements.py#L33

The NaNs mean that there isn't data for the column at that time. Since raw eeg has a very high sampling rate (512Hz), you'll see many rows with NaNs before you get some with the other values since they have a very low sampling frequency of about 1Hz.

**Comment by saipm1** [comment]
I have commented L39 -  https://github.com/gmierz/mindwave-lsl/blob/master/mindwavelsl/mindwavelsl.py#L39 - empty csv file is created. No data is written to it.

**Comment by gmierz** [comment]
Oh, try removing this: `"enableRawOutput": true,` from that line. From these docs: http://developer.neurosky.com/docs/doku.php?id=thinkgear_socket_protocol

By the way, are you using the Mindwave Mobile 2 or something else?

**Comment by gmierz** [comment]
@saipm1 were you able to get it working?

**Comment by saipm1** [comment]
If I used the options that you suggested no output was generated. However I noticed that I used the code as it is it was generating the values after some time. But I think the output is very chatty. I am not sure how to make a meaningful report out of the date. PFA the sample file that I generated after 10 min output. Please review and let me know if I am missing something here.
[mindwave-output.zip](https://github.com/gmierz/mindwave-lsl/files/6331303/mindwave-output.zip)

**Comment by gmierz** [comment]
Closing as inactive, please file a new issue if you're still having problems.
